---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/gorel/public_html/apicomunidades.regionloreto.gob.pe/
      - /bin/rsync -av public/ $DEPLOYPATH
      - export DEPLOYPATH=/home/gorel/web_apicomunidades/
      - /bin/rsync -av ./ $DEPLOYPATH