---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/gorel/public_html/pueblosoriginarios.regionloreto.gob.pe/panel
      - /bin/rsync -av public/ $DEPLOYPATH
      - export DEPLOYPATH=/home/gorel/web_pueblosoriginarios/
      - /bin/rsync -av ./ $DEPLOYPATH